apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::296134751514:role/node-group-2-eks-node-group-20230927102343213300000002
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::296134751514:role/node-group-1-eks-node-group-20230927102343211400000001
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::296134751514:user/eda-seppar
      username: eda-seppar
      groups:
        - system:masters
    - userarn: arn:aws:iam::296134751514:user/james-walsh
      username: james-walsh
      groups:
        - system:masters
    - userarn: arn:aws:iam::296134751514:user/james-whitburn
      username: james-whitburn
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-27T10:32:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1014"
  uid: 514672f5-0210-4911-8a10-da59f9484e9b
